### ISSUE TITLE
5.30-mod_fcgid is absent

### ISSUE THREAD

**Issue by yselkowitz** [sclorg/s2i-perl-container#195]
Despite the release of RHEL/UBI 8.3 with a perl-530 mod_fcgid image, a corresponding directory is missing from this repository.

**Comment by ppisar** [comment]
I will send a pull request.

**Comment by ppisar** [comment]
@pkubatrh, what base image should I refer in FROM? ubi8/s2i-base:1 or ubi8/s2i-base:rhel8.3? The underlying perl:5.30 module is available since RHEL-8.3.

**Comment by pkubatrh** [comment]
`ubi8/s2i-base:1`, the `:rhel8.3` tag is only available internally.

And thanks for taking care of the PR!

**Comment by ppisar** [comment]
Fixed with 770674e7367ec9fd8e1b0e1553c98299cc90808d.
