### ISSUE TITLE
publish fedora-based container on registry.fedoraproject.org

### ISSUE THREAD

**Issue by ibotty** [sclorg/s2i-perl-container#204]
I cannot find any published image on registry.fedoraproject.org.

I can try to push it forward myself but would need guidance on where to start.

**Comment by ppisar** [comment]
I have no idea how images for Fedora are built and published. But what prevented perl images from building in the past was that Fedora did not contain the needed Modularity modules and Perl versions. Now Fedora ≥ 34 contains all the necessary stuff. But I worry that the underlying Fedora images (s2i-base etc.) are require an older Fedora (e.g. 33).

**Comment by pkubatrh** [comment]
Yeah, one issue is that s2i-core and s2i-base are not yet built for f34, but that can now be done after having F33 branched.

For the perl image if the underlying modules are available now we would first need to add a [new version](https://github.com/sclorg/welcome/blob/master/contribution.md#adding-a-new-version) (3.22) in this repository that contains the Fedora-based Dockerfile built on top of f34/s2i-base.
After that the sources need to be synced downstream to the [Fedora's dist-git.](https://src.fedoraproject.org/container/perl) This can be done manually, or with [cwt](https://github.com/sclorg/container-workflow-tool) (`cwt --do-image perl git pullupstream`), but cwt will be missing the configs for f34.
The build and publishing of the resulting image is done similarly to how rpms are done.

We will get to all of it eventually, but if you would like to help with any of the steps I would be glad to review any PRs you might prepare. :)

**Comment by phracek** [comment]
This can be close. perl-5.32 is published here https://quay.io/repository/fedora/perl-532

**Comment by phracek** [comment]
The rest containers like perl-5.34 will be published there as well. Like https://quay.io/repository/fedora/perl-534

**Comment by michal-josef-spacek** [comment]
@phracek What about perl-5.30? We have it in repository, but not in quay.io. Same perl-5.26.
