### ISSUE TITLE
s21-perl-container is failing with DBD::mysql 5.x

### ISSUE THREAD

**Issue by jplesnik** [sclorg/s2i-perl-container#285]
### Version

All versions

### Description

On all version, `test_from_dockerfile` is failing. 
It uses `dancer-ex` which install `DBD::mysql` directly from `CPAN`. 
`DBD::mysql` requires `MySQL 8.x` for build since version 5.x, but the container contains `mariadb`.

The recommendation is replace using `DBD::MariaDB` instead of `DBD::mysql`.

**Comment by michal-josef-spacek** [comment]
Issue is fixed and tested
