### ISSUE TITLE
Standard Perl environment variable $PERL5LIB missing from built images

### ISSUE THREAD

**Issue by nhr** [sclorg/s2i-perl-container#71]
At the end of the assemble process, the builder should set up the `PERL5LIB` variable so that it is available to built applications. The purpose of this variable is to extent perl's default module lookup paths with ones that were added through other means. In this case it would be used to look up paths introduced by `cpanm`-driven package installations. This is valuable because it is a pretty standard part of a Perl runtime environment, and also means that devs will not need to adjust their code for the specific module paths that we set up in our containers.

**Comment by ppisar** [comment]
On Thu, Feb 25, 2016 at 08:46:42AM -0800, N. Harrison Ripps wrote:
> At the end of the assemble process, the builder should set up the `PERL5LIB`
> variable so that it is available to built applications.

The variable and other ones are set in the run script, so that is available
when running the assembled image.

> In this case it would be used to look up paths introduced by `cpanm`-driven
> package installations. This is valuable because it is a pretty standard part
> of a Perl runtime environment, and also means that devs will not need to
> adjust their code for the specific module paths that we set up in our
> containers.
>
The location is specific to s2i-driven deployment. If you use your own
mechanims, it's up to you to set the variable to location of your choice.

**Comment by rhcarvalho** [comment]
> The variable and other ones are set in the run script, so that is available
> when running the assembled image.

If it is set in the run script, I understand it won't be available for users of `oc exec`, `oc rsh`, etc.

Anyway, exporting it in the assemble script won't make it available/baked into the image, as the shell environment is not committed, just the disk state. As an example, the perl assemble script exports CPAN_MIRROR, and it is not available in a image built with the perl builder (using the dancer-ex repo).

If the value of PERL5LIB is a constant, we shall set it in the Dockerfile, just like we set PERL_VERSION.

Do ya'll agree with this approach?

**Comment by mfojtik** [comment]
@rhcarvalho I think that is reasonable.

**Comment by ppisar** [comment]
On Fri, Feb 26, 2016 at 01:20:17AM -0800, Rodolfo Carvalho wrote:
> If the value of PERL5LIB is a constant, we shall set it in the Dockerfile,
> just like we set PERL_VERSION.
> 
> Do ya'll agree with this approach?
> 
It looks good as long as you use the base image in the s2i way. If you don't,
what is also another supported use case, then you actually hard-codes
a location and that can be unexpected for the user and therefore a possible
security issuse.

Therefore I must disagree.

Clean solution is add the variable the application image. Not into the s2i
image.

**Comment by rhcarvalho** [comment]
> as long as you use the base image in the s2i way

Sorry I don't understand what that means. What is "the s2i way"?

**Comment by ppisar** [comment]
On Fri, Feb 26, 2016 at 01:49:51AM -0800, Rodolfo Carvalho wrote:
> > as long as you use the base image in the s2i way
> 
> Sorry I don't understand what that means. What is "the s2i way"?

You start with an s2i-capable image, this is the image build from this
repository against this bug was reported.

Than you either use this image in whatever way you want, or you use s2i tool
to build an application image and then run the application image. For example
you exec into the application image (this your use case). The second method
I referred a "the s2i way".

But I have a solution. We can define the variable in
/opt/app-root/etc/scl_enable. Then the variable will be presented in the
application image even when executing into it. And it will not be in the
s2i-capable image because it does not execute the /opt/app-root/etc/scl_enable
as an docker entry point.

**Comment by rhcarvalho** [comment]
> And it will not be in the
> s2i-capable image because it does not execute the /opt/app-root/etc/scl_enable
> as an docker entry point.

Sorry I am not sure I understood. The entrypoint is never set to `/opt/app-root/etc/scl_enable`, is it?
By "s2i-capable" image, do you mean a builder image?

Hmmm, perhaps, are you talking about `docker build` vs. `s2i build`?


> Than you either use this image in whatever way you want, or you use s2i tool
> to build an application image and then run the application image.

What is wrong with setting the env var in the Dockerfile?
Is there a scenario where setting PERL5LIB to `/opt/app-root/src/extlib/lib/perl5` would be wrong and prevent using the image?


> But I have a solution. We can define the variable in
> /opt/app-root/etc/scl_enable. Then the variable will be presented in the
> application image even when executing into it.

I wouldn't make changing `scl_enable` my first choice. That's a hack I'm not proud of, that tries to overcome inconveniences for users of the image, but only works and sort of forces users to always wrap everything in a shell invocation (and it doesn't work with `/bin/sh -c`).

It should only be used for enabling collections, for we so far have no way to enable them globally in the image.

**Comment by mfojtik** [comment]
@rhcarvalho I think his point is that if we do that then the system perl might be muted for perl scripts installed in /usr/bin, etc...

**Comment by rhcarvalho** [comment]
Quoting @nhr:

> The purpose of this variable is to extent perl's default module lookup paths with ones that were added through other means.

I assumed it is just extending the lookup paths, not replacing?

**Comment by rhcarvalho** [comment]
The behavior is indeed *extending* the default paths: http://www.perlhowto.com/extending_the_library_path

@nhr @ppisar is there any problem with having in the Dockerfile:
```Dockerfile
ENV PERL5LIB=/opt/app-root/src/extlib/lib/perl5
```

?

If the directory does not exist Perl just simply ignore it, right?

**Comment by ppisar** [comment]
On Fri, Feb 26, 2016 at 04:57:48AM -0800, Rodolfo Carvalho wrote:
> The behavior is indeed *extending* the default paths: http://www.perlhowto.com/extending_the_library_path
> 
> @nhr @ppisar is there any problem with having in the Dockerfile:
> ```Dockerfile
> ENV PERL5LIB=/opt/app-root/src/extlib/lib/perl5
> ```
> 
OMG. I've already said that's a problem. I don't have time to implement it now.
Wait few days.

**Comment by nhr** [comment]
First off, let me note that in researching this further, setting PERL5LIB is actually not the right approach to solving this problem. Per [this PerlMonks article](http://www.perlmonks.org/bare/?node_id=303052), PERL5LIB is actually ignored within the mod_perl runtime environment, The recommended way to introduce additional module search paths to the Perl @INC list is via the `PerlSwitches` directive in the [apache configuration](https://perl.apache.org/docs/2.0/user/config/config.html#C_PERL5LIB__and_C_PERLLIB__Environment_Variables). 

Here is my proposal for how to do this. This approach actually solves two issues, because it would reintroduce a desirable behavior that cpanminus lacks (by design, but still lacks).

1. Modify the assemble script so that instead of leaving `cpanm` to consume the cpanfile contents on its own, we iterate over each line of cpanfile and call `cpanm` for each item.

2. After each invocation of cpanm, look at which directories get created under /opt/app-root/src/. Why? [In the case of my application](https://github.com/nhr/swn/blob/master/CGI/seed.cgi#L9-L10), extlib/lib/perl5 wasn't the only path created, so this exercise would allow us to capture every path that cpanm creates. **But also**, it enables the user to enforce an installation order of the required modules. Again, in the case of my app, I had to create a custom builder to work around the fact that [one module](https://github.com/nhr/swn/blob/master/cpanfile#L9) depends upon [another](https://github.com/nhr/sti-perl-swn/blob/master/Dockerfile#L12), but has not been updated such that cpanm correctly resolves the dependency.

Given that my app dependencies [built without issue in v2](https://github.com/nhr/swn/blob/v1.0/.openshift/cpan.txt) (which used cpan shell vs. cpanminus), I think this will make for a better developer experience.

3. After looping through the dependencies, we'll know which paths need to be added to @INC. At this point, in an ideal world, we would go back and add a `PerlSwitches` line in httpd.conf. However, if that is not possible during the assemble stage, an alternative would be to create or add to an existing .htaccess file in every directory of the user's source code where a .pl or .cgi file is found.

I am tagging @knobunc to review this proposed solution with regards to what is the right way to add module search paths in the context of Apache + mod_perl, and to laugh at my atrophied Perl skills.

**Comment by knobunc** [comment]
PERL5LIB is only dropped when perl is running in taint mode.  I'm not sure if we set it up that way with s2i.

However, mod_perl probably doesn't import the PERL5LIB from the environment, but you can use the PassEnv directive to allow it to be used.  Or you can just set it directly with SetEnv.

It would be nice to have PERL5LIB set in case the apache process forks a child and execs a perl program...

I don't know how we are using cpanminus, but aren't we telling it to install all the libraries into the same tree?

**Comment by nhr** [comment]
Thanks @knobunc - so, in support of having a PERL5LIB available for forked Perl processes, I submit that steps 1 and 2 in my proposal stand, but for step 3 rather than using `PerlSwitches` we would ideally:

* Set PERL5LIB in the [s2i run exec line](https://github.com/openshift/sti-perl/blob/master/5.20/s2i/bin/run#L26)
* Configure apache with `PassEnv` such that PERL5LIB is available to httpd-invoked Perl code.

Regarding the question:

> I don't know how we are using cpanminus, but aren't we telling it to install all the libraries into the same tree?

In my app, cpanminus actually created two paths. To me the belt-and-suspenders approach, then, would be to just detect newly created module paths as we assemble.

**Comment by hhorak** [comment]
@ppisar This got stalled for long time, what is your take on it?

**Comment by ppisar** [comment]
My take is decline it.

The /opt/app-root/src/extlib/ directories are added into PERL5LIB and PATH variables in the run script. It's not done in Dockerfile because it would affect scripts using system Perl. This is the same reason why "scl enable"-affected variables are not precomputed in the Dockerfile.

If you need the variables on the image level, you will have to add them there manually after running the assemble script. Or ask s2i tool developers to add such a capability into s2i tool.
